# Generated by Django 5.2.8 on 2025-11-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('index_page_image', models.ImageField(upload_to='site_images/')),
                ('copyright_text', models.CharField(max_length=200)),
            ],
        ),
    ]
