# Generated by Django 5.2.8 on 2025-11-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='sub_title',
            field=models.CharField(default='subtitle', max_length=220),
        ),
    ]
