# Generated by Django 5.2.8 on 2025-11-19 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_socialicon_siteinfo_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialicon',
            name='site_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.siteinfo'),
        ),
    ]
