# Generated by Django 5.2.8 on 2025-11-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='sub_tile',
            new_name='sub_title',
        ),
    ]
